### ISSUE TITLE
File Diff Colour

### ISSUE THREAD

**Issue by TVProduction** [friebetill/obsidian-file-diff#1]
File diff is fabulous; I can see it being one of those essential plugins.  (Previously, I was comparing files outside of Obsidian.)  A minor question: is there any way to adjust the colour of the changes.  I tend to work in a dark theme and blue is washed out.

**Comment by friebetill** [comment]
Thank you very much for your kind words! I released a new update with which you can easily update the colors. 

To do this, you need to follow these steps: 
1. Create a new CSS file in the folder `.obsidian/snippets`, e.g. `file-diff.css`. 
2. Fill the CSS file with the following and update the colors accordingly: 
```css
@media (prefers-color-scheme: light) {
	.file-diff__top-line__bg {
		background-color: #d9f4ef;
	}

	.file-diff__bottom-line__bg {
		background-color: #d9edff;
	}

	.file-diff__button-danger {
		background-color: #b00020 !important;
		color: #ffffff;
	}

	.file-diff__button-danger:hover {
		background-color: #9f0020 !important;
		color: #ffffff;
	}

	.file-diff__action-line {
		color: #919191;
	}
}

@media (prefers-color-scheme: dark) {
	.file-diff__top-line__bg {
		background-color: #25403b;
	}

	.file-diff__bottom-line__bg {
		background-color: #25394b;
	}

	.file-diff__button-danger {
		background-color: #cf6679 !important;
		color: #ffffff;
	}

	.diff__button-danger:hover {
		background-color: #b85a6d !important;
		color: #ffffff;
	}

	.file-diff__action-line {
		color: #919191;
	}
}
```
3. Activate the CSS file in the settings under **Appearance**.

**Comment by Eusorph** [comment]
Absolutely fantastic and I discovered it works in real time as I type, so it basically a track changes that is very simple and useful to use. Thanks so much!

**Comment by Eusorph** [comment]
I was able do what I wanted with this snippet. Is it OK?

@media (prefers-color-scheme: light) {
	.file-diff__top-line__bg {
		background-color: #e6f5f2;
		border-radius: 0.25rem; /* 4px */
	}

	.file-diff_top-line__character {
		background-color: #67c9f0;
		border-radius: 0.25rem; /* 4px */
		text-decoration: underline;
	}

	.file-diff__bottom-line__bg {
		background-color: #ecf6ff;
		border-radius: 0.25rem; /* 4px */
	}

	.file-diff_bottom-line__character {
		background-color: #f76767;
		border-radius: 0.25rem; /* 4px */
		text-decoration: line-through;
	}
}

**Comment by Eusorph** [comment]
One last thing. When I run the command file dff: compare and choose a file, in the compare window I see my initial file at the bottom and file I asked to compare at the top. Personally I would prefer to see the file I start the command from at the top and the file I asked to compare at the bottom. Is there any way to achies this?

**Comment by merlinuwe** [comment]
Thanks for this useful plugin. Here is another idea. Works with Obsidian v.1.8.10 and File Diff 1.1.1 (If you like it, you can use it in this plugin or what you want.)

![Image](https://github.com/user-attachments/assets/20fd104c-046f-4347-85c7-bf5d4f050891)

![Image](https://github.com/user-attachments/assets/4ac97f0f-6548-4d33-8f17-85b5817f9f4b)

```css
/*
 * ===================================================================
 *  CSS für das Obsidian File Diff Plugin
 * ===================================================================
*/


:root {
  /* Globale Design-Tokens */
  --diff-border-radius: 5px;
  --diff-spacing: 4px;
  --diff-transition-speed: 0.2s;

  /* --- Light Mode Palette --- */
  --diff-add-bg-light: #f0fdf4;
  --diff-add-border-light: #bbf7d0;
  --diff-add-shadow-light: rgba(22, 163, 74, 0.1);
  --diff-add-label-color-light: #15803d;
  --diff-add-char-bg-light: #bbf7d0;

  --diff-del-bg-light: #fff1f2;
  --diff-del-border-light: #fecdd3;
  --diff-del-shadow-light: rgba(220, 38, 38, 0.1);
  --diff-del-label-color-light: #b91c1c;
  --diff-del-char-bg-light: #fecdd3;

  /* --- Dark Mode Palette --- */
  --diff-add-bg-dark: #05140a;
  --diff-add-border-dark: #14532d;
  --diff-add-shadow-dark: rgba(34, 197, 94, 0.15);
  --diff-add-label-color-dark: #4ade80;
  --diff-add-char-bg-dark: #166534;

  --diff-del-bg-dark: #1f0808;
  --diff-del-border-dark: #7f1d1d;
  --diff-del-shadow-dark: rgba(239, 68, 68, 0.15);
  --diff-del-label-color-dark: #f87171;
  --diff-del-char-bg-dark: #991b1b;
}


/*
 * ---------------------------------
 *  Implementierung des Designs
 * ---------------------------------
*/

/* --- Allgemeines Layout der Zeilen --- */
:is(.file-diff__top-line__bg, .file-diff__bottom-line__bg) {
  display: flex; align-items: center; margin: 0 0 var(--diff-spacing) 0; min-height: 1.8em; padding: 0.4em 0.8em;
  border-radius: var(--diff-border-radius); border: 1px solid;
  transition: all var(--diff-transition-speed) ease-in-out;
}
.file-diff__top-line__bg { background-color: var(--diff-add-bg-light); border-color: var(--diff-add-border-light); box-shadow: inset 0 1px 1px var(--diff-add-shadow-light); }
.file-diff__bottom-line__bg { background-color: var(--diff-del-bg-light); border-color: var(--diff-del-border-light); box-shadow: inset 0 1px 1px var(--diff-del-shadow-light); text-decoration: line-through; }
.theme-dark .file-diff__top-line__bg { background-color: var(--diff-add-bg-dark); border-color: var(--diff-add-border-dark); box-shadow: inset 0 1px 2px var(--diff-add-shadow-dark); }
.theme-dark .file-diff__bottom-line__bg { background-color: var(--diff-del-bg-dark); border-color: var(--diff-del-border-dark); box-shadow: inset 0 1px 2px var(--diff-del-shadow-dark); }

/* --- Elegante "Ghost"-Labels --- */
:is(.file-diff__top-line__bg, .file-diff__bottom-line__bg)::before {
  display: inline-block; font-weight: 600; padding: 0.2em 0.8em; margin-right: 1.2em;
  border-radius: var(--diff-border-radius); border: 1px solid; background-color: transparent !important;
  text-decoration: none !important; transition: all var(--diff-transition-speed) ease-in-out;
}
.file-diff__top-line__bg::before { content: "+ Ergänzt"; color: var(--diff-add-label-color-light) !important; border-color: var(--diff-add-label-color-light) !important; }
.file-diff__bottom-line__bg::before { content: "- Gelöscht"; color: var(--diff-del-label-color-light) !important; border-color: var(--diff-del-label-color-light) !important; }
.theme-dark .file-diff__top-line__bg::before { color: var(--diff-add-label-color-dark) !important; border-color: var(--diff-add-label-color-dark) !important; }
.theme-dark .file-diff__bottom-line__bg::before { color: var(--diff-del-label-color-dark) !important; border-color: var(--diff-del-label-color-dark) !important; }

/* Gemeinsame Stile für Hervorhebungen zuerst definieren */
:is(.file-diff_top-line__character, .file-diff_bottom-line__character) {
  padding: 0.1em 0.2em;
  border-radius: 0.25rem;
  color: inherit !important;
  font-weight: bold; /* Für bessere Sichtbarkeit */
  transition: background-color var(--diff-transition-speed) ease-in-out;
}
/* Jetzt nur noch die spezifischen Hintergrundfarben zuweisen */
.file-diff_top-line__character { background-color: var(--diff-add-char-bg-light) !important; }
.file-diff_bottom-line__character { background-color: var(--diff-del-char-bg-light) !important; }
.theme-dark .file-diff_top-line__character { background-color: var(--diff-add-char-bg-dark) !important; }
.theme-dark .file-diff_bottom-line__character { background-color: var(--diff-del-char-bg-dark) !important; }


/* --- Sonderfälle --- */
/* Styling für das Leerzeilen-Symbol */
:is(.file-diff__top-line__bg, .file-diff__bottom-line__bg):empty::after {
  content: '\21B5'; 
  opacity: 0.5; 
  text-decoration: none;
  font-weight: normal; /* Das Symbol selbst soll nicht fett sein */
}
```
